### ISSUE TITLE
std::foo_algorithm is more specialized than ranges::foo_algorithm

### ISSUE THREAD

**Issue by CaseyCarter** [CaseyCarter/cmcstl2#12]
The calls to three-argument equal with an argument that has `std` as an associated namespace need explicit qualification to disambiguate, e.g., [Line 219](https://github.com/CaseyCarter/cmcstl2/blob/master/test/algorithm/equal.cpp#L219):

``` c++
CHECK(stl2::equal(make_range(input_iterator<const int*>(ia),
                             sentinel<const int*>(ia+s)),
                  make_range(input_iterator<const int*>(ia),
                             sentinel<const int*>(ia + s)),
                  std::equal_to<int>()));
```

The stl2 overloads of `equal` are obviously more-constrained. Determine why the std overloads are being selected by overload resolution, and develop a plan to correct the problem.

**Comment by CaseyCarter** [comment]
> Determine why the std overloads are being selected by overload resolution

In the noted call expression, the first and second arguments are ranges of the same type. The 3-legged `std::equal` overload is therefore viable and more specialized than the `ranges::equal` overload that accepts two ranges of differing types. 

The fix would be to define equally-specialized-and-more-constrained signatures for all such algorithms.

**Comment by CaseyCarter** [comment]
> The fix would be to define equally-specialized-and-more-constrained signatures for all such algorithms.

Which requires roughly doubling the number of algorithm declarations since every iterator/sentinel algorithm declaration has the same problem of being less specialized than its iterator/iterator counterpart in namespace `std`. range-v3 sidesteps the issue by using function object algorithms which break ADL; I suppose users of the Ranges TS must simply become accustomed to explicitly qualifying any function name that also exists in namespace `std`.

**Comment by ericniebler** [comment]
I'm curious why this issue isn't in the stl2 tracker.

**Comment by CaseyCarter** [comment]
I initially thought this was a concepts bug. I had forgotten about it completely until I saw your issue mention ADL. I'll migrate it since it's a significant usability issue and it can receive some attention.

**Comment by CaseyCarter** [comment]
Migrated into the stl2 tracker.
