### ISSUE TITLE
max does not compile in a constexpr context

### ISSUE THREAD

**Issue by cjdb** [CaseyCarter/cmcstl2#124]
It appears that `std::experimental::ranges::max` doesn't work inside constexpr lambdas. Sample code: https://godbolt.org/g/qp8jFP.

**Comment by CaseyCarter** [comment]
My first implementation of `invoke` was `constexpr`. I later changed that to agree with the non-`constexpr` specification of `invoke` in the TS, but forgot to fix the `constexpr` algorithms to use the super-secret `constexpr` backdoor `__invoke::impl`.
