### ISSUE TITLE
Ridiculous compile time for alg.find_end

### ISSUE THREAD

**Issue by CaseyCarter** [CaseyCarter/cmcstl2#13]
On my machine, alg.find_end takes just over a minute to compile; that's around a third of the full test run compile time just for this test.

**Comment by ericniebler** [comment]
Is this related to your changes to `begin`/`end `?

**Comment by CaseyCarter** [comment]
Yes - it wouldn't compile at all before the memoization changes. It would fill the 7G of virtual memory in my VirtualBox and the Linux kernel OOM killer would kill the compiler. It's probably a similar issue with multiple redundant constraints on the many `find_end` overloads that could be worked around with some clever memoization.

**Comment by CaseyCarter** [comment]
1c4621517edf7e3265b032fa35b56dbc280e4cac is a 40% speedup - still slower than I'd like.

**Comment by CaseyCarter** [comment]
cf293325418741d8f698b3fd43cb40559d4ae61c is memoization taken to the extreme - pushed as far as possible without obscuring subsumption relationships between concepts. The concepts are effectively decomposed into conjunctions of memoizable traits. alg.find_end compiles in 15 seconds. 

It is, however, not strictly conforming. Since the expressions are all hidden from the compiler, it won't know that e.g. an overload that requires `a == b` is strictly less specialized than an overload that requires `EqualityComparable<decltype(a), decltype(b)>()`. I hate to commit something so "loosely" conformant, but we're rapidly outscaling the compiler's capabilites.

**Comment by CaseyCarter** [comment]
Merged the memoization branch to master in 8650909a1dcd733d0b8d8c8b5562c59ab0c849e8. For the time being, we need a working reference implementation more than we need strict conformance.
