### ISSUE TITLE
__construct_at and references

### ISSUE THREAD

**Issue by TartanLlama** [CaseyCarter/cmcstl2#132]
@cjdb and I were discussing the possible standardisation of `construct_at` and came across an issue, so he told me to submit a report.

`__construct_at` takes a reference to the place where `T` should be constructed, but this will be undefined behaviour if something is passed which is not a valid `T` object due to [dcl.ref]/5:

> There shall be no references to references, no arrays of references, and no pointers to references. The declaration of a reference shall contain an initializer ([dcl.init.ref]) except when the declaration contains an explicit extern specifier ([dcl.stc]), is a class member declaration within a class definition, or is the declaration of a parameter or a return type ([dcl.fct]); see [basic.def]. **A reference shall be initialized to refer to a valid object or function.** [ Note: In particular, a null reference cannot exist in a well-defined program, because the only way to create such a reference would be to bind it to the “object” obtained by indirection through a null pointer, which causes undefined behavior. As described in [class.bit], a reference cannot be bound directly to a bit-field. — end note ]

http://eel.is/c++draft/dcl.ref#5.sentence-3

An example would be `std::aligned_storage_t<sizeof(T), alignof(T)>`, which is storage capable of holding a `T`, but not a valid `T` object.

This can, of course, be fixed by taking a pointer instead of a reference.

I don't know if this'll cause you problems practically or if you'll have any desire to fix it, but thought I'd submit the issue all the same :)

**Comment by CaseyCarter** [comment]
> You can't bind a reference where an object doesn't yet exist!

This is [CWG 453](https://wg21.link/cwg453), for which the current PR (and other PRs going back to 2004) makes it valid to bind a reference to a region of memory of size-and-alignment appropriate to provide storage for the referenced type. Practically speaking, I prefer the implementation that accepts a reference to one that accepts a pointer:

1. The function is useful for implementing standard containers, and accepting references sidesteps the entire issue of how poorly specified fancy pointers are
1. Standard library implementors don't get to use `&`, and `construct_at(addressof(foo.storage), arg1, arg2)` is *way* more typing than `construct_at(foo.storage, arg1, arg2)`

Given that both of these are "convenience for library implementor" arguments, I suspect WG21 would reject them and ask for a design that takes a pointer parameter if someone were to propose `construct_at` for standardization.

(Fun fact: `aligned_storage` cannot be implemented in C++. Only class types can have alignments applied to them with `alignas`, but only arrays of `unsigned char` and `byte` can "provide storage".)

**Comment by CaseyCarter** [comment]
> Given that both of these are "convenience for library implementor" arguments, I suspect WG21 would reject them and ask for a design that takes a pointer parameter if someone were to propose `construct_at` for standardization.

Not to mention the fact that `destroy_at` takes a pointer; *I* would probably reject a proposal for `construct_at` that accepted a reference.

**Comment by TartanLlama** [comment]
Cool, thanks for that CWG issue!
