### ISSUE TITLE
istreambuf_iterator constructed with istream at eof isn't detected

### ISSUE THREAD

**Issue by cjdb** [CaseyCarter/cmcstl2#149]
When comparing a freshly-constructed `istreambuf_iterator` with an `istream` that has already reached EOF, `istreambuf_iterator != default_sentinel` returns `true`. This behaviour differs from `std::istreambuf_iterator`.

```cpp
#include <experimental/ranges/iterator>
#include <iostream>
#include <sstream>

int main()
{
   auto in = std::istringstream{"hello"};
   for (auto i = __stl2::istreambuf_iterator<char>{in}; i != __stl2::default_sentinel{}; ++i) {
      std::cout << *i << '\n';
   }
   for (auto i = __stl2::istreambuf_iterator<char>{in}; i != __stl2::default_sentinel{}; ++i) {
      std::cout << *i << '\n';
   }
}
```

Interestingly, this is only on the first pass: commenting out line 16 causes the program to complete without error.

**Comment by CaseyCarter** [comment]
> commenting out line 16

I only count 14 lines.

**Comment by cjdb** [comment]
>I only count 14 lines.

Ahh! I took a few lines out from GitHub, but not my editor. Should be line 12.

**Comment by cjdb** [comment]
This might be related to #28.

**Comment by CaseyCarter** [comment]
`istreambuf_iterator` is, unsuprisingly, broken. [[istreambuf.iterator.cons]](http://eel.is/c++draft/istreambuf.iterator.cons):

> 1 For each `istreambuf_­iterator` constructor in this subclause, **an end-of-stream iterator is constructed if and only if the exposition-only member `sbuf_`­ is initialized with a null pointer value**.
> ```c++
> constexpr istreambuf_iterator() noexcept;
> ```
> 2 *Effects:* Initializes `sbuf_­` with `nullptr`.
> ```c++
> istreambuf_iterator(istream_type& s) noexcept;
> ```
> 3 *Effects:* Initializes `sbuf_­` with `s.rdbuf()`.
> ```c++
> istreambuf_iterator(streambuf_type* s) noexcept;
> ```
> 4 *Effects:* Initializes `sbuf_­` with `s`.
> ```c++
> istreambuf_iterator(const proxy& p) noexcept;
> ```
> 5 *Effects:* Initializes `sbuf_­` with `p.sbuf_­`.

[[istreambuf.iterator.ops]](http://eel.is/c++draft/istreambuf.iterator.ops) para 5 & 6:

> ```c++
> bool equal(const istreambuf_iterator& b) const;
> ```
> 5 *Returns:* `true` if and only if both iterators are at end-of-stream, or neither is at end-of-stream, > regardless of what streambuf object they use.
> ```c++
> template<class charT, class traits>
>   bool operator==(const istreambuf_iterator<charT,traits>& a,
>                   const istreambuf_iterator<charT,traits>& b);
> ```
> 6 *Returns:* `a.equal(b)`

Yet this program:
```c++
#include <cassert>
#include <iterator>
#include <sstream>

int main()
{
   auto in = std::istringstream{};
   using I = std::istreambuf_iterator<char>;
   assert(in.rdbuf() != nullptr);
   // Since in.rdbuf() != nullptr, I{in} does not construct an end-of-stream iterator.
   assert(I{in} != I{}); 
}
```
Fails on on libstdc++/libc++/STLSTL.
