### ISSUE TITLE
value_type<T> does not return value type of a pointer

### ISSUE THREAD

**Issue by UniversE** [CaseyCarter/cmcstl2#275]
The current working draft suggests (iterator.assoc.types.value_type) that value_type should have a specialization like this for pointer types:
```C++
template <class T>
struct value_type<T*>
: enable_if<is_object<T>::value, remove_cv_t<T>> { };
```

This specialization seems to be missing from this implementation. The below example code does only compile, if I add this specialization manually.

Full example for demonstration:
```C++
#include <experimental/ranges/concepts>
#include <experimental/ranges/iterator>

using namespace std::experimental::ranges::v1;


// Uncomment the sepcialization to make the static assert work.
/*
namespace std::experimental::ranges::v1::cursor {
template<class T>
struct value_type<T*>
: enable_if<is_object<T>::value, remove_cv_t<T>> { };
}
*/

static_assert(std::is_same_v<typename cursor::value_type_t<int*>, int>);
```

**Comment by CaseyCarter** [comment]
The current C++ working draft is [N4800](https://github.com/cplusplus/draft/blob/master/papers/n4800.pdf). It has no subclause [iterator.assoc.types.value_type]; `value_type` became `readable_traits` as part of [P1037r0 "Deep Integration"](http://wg21.link/p1037r0) which was integrated into [P0896R4 "The One Ranges Proposal"](http://wg21.link/p0896r4) that was finally merged into the C++ working draft.

`std::experimental::ranges::readable_traits` *does* have [a specialization for pointer types](https://github.com/CaseyCarter/cmcstl2/blob/master/include/stl2/detail/iterator/concepts.hpp#L113-L114) as specified in [[readable.traits]](http://eel.is/c++draft/readable.traits) in the working draft.

(Everything in the `cursor` subnamespace is an implementation detail of `basic_iterator` from the stalled [P0186 "Iterator Facade Library Proposal for Ranges"](http://wg21.link/p0186).)

**Comment by UniversE** [comment]
Thank you for the quick response and apologies for the inconvenience. There seems still to be too many outdated information on the internet and shame on me I did not search hard enough for the most recent stuff....
