### ISSUE TITLE
Missing `operator*` in basic_iterator

### ISSUE THREAD

**Issue by asutton** [CaseyCarter/cmcstl2#34]
Some concept, somewhere, uses `*declval<const I&>()` with `I` being a `basic_iterator`. Because it doesn't have a `const` overload of `operator*`, the program is ill-formed.

Patch here: https://gist.github.com/asutton/c381a942e02c3f4c8335cfc25d57bd00

**Comment by CaseyCarter** [comment]
`Readable` requires a `const` overload of `operator*`, `Writable` allows `operator*` to mutate. If "some concept, somewhere" thinks that a non-`Readable` iterator must have `operator*() const`, *that* is the bug that needs to be fixed.

I'll respond to the separate email to work out how to repro this.

**Comment by asutton** [comment]
Built using this version of GCC: https://github.com/gcc-mirror/gcc/tree/jason/concepts-rewrite. Include the disable-opt.diff and tsubst.diff patches from the GCC patches list https://gcc.gnu.org/ml/gcc-patches/2016-07/msg00464.html.

The error appears to originate from `counted_iterator` when compiling (at least) the generate.cpp test case. The `noexcept` specifier includes `*declval<const I&>())`, which fails to find a const overload for `basic_iterator`.

In file included from /Users/Sutton/Code/cmcstl2/include/stl2/iterator.hpp:25:0,
                 from /Users/Sutton/Code/cmcstl2/include/stl2/detail/algorithm/generate.hpp:15,
                 from /Users/Sutton/Code/cmcstl2/test/algorithm/generate.cpp:21:
/Users/Sutton/Code/cmcstl2/include/stl2/detail/iterator/counted_iterator.hpp: In instantiation of ‘decltype(auto) std::experimental::ranges::v1::__counted_iterator::cursor<I>::read() const requires (InputIterator<I>)() [with I = std::experimental::ranges::v1::basic_iterator<std::experimental::ranges::v1::detail::back_insert_cursor<std::vector<int> > >]’:
/Users/Sutton/Code/cmcstl2/include/stl2/detail/iterator/basic_iterator.hpp:164:9:   required from ‘class std::experimental::ranges::v1::basic_iterator<std::experimental::ranges::v1::__counted_iterator::cursor<std::experimental::ranges::v1::basic_iterator<std::experimental::ranges::v1::detail::back_insert_cursor<std::vector<int> > > > >’
/Users/Sutton/Code/cmcstl2/include/stl2/detail/iterator/counted_iterator.hpp:197:27:   required from ‘auto std::experimental::ranges::v1::make_counted_iterator(I&&, std::experimental::ranges::v1::difference_type_t<typename std::decay<_Tp>::type>) [with I = std::experimental::ranges::v1::basic_iterator<std::experimental::ranges::v1::detail::back_insert_cursor<std::vector<int> > >; std::experimental::ranges::v1::difference_type_t<typename std::decay<_Tp>::type> = long int]’
/Users/Sutton/Code/cmcstl2/test/algorithm/generate.cpp:76:60:   required from here
/Users/Sutton/Code/cmcstl2/include/stl2/detail/iterator/counted_iterator.hpp:111:25: error: passing ‘const std::experimental::ranges::v1::basic_iterator<std::experimental::ranges::v1::detail::back_insert_cursor<std::vector<int> > >’ as ‘this’ argument discards qualifiers [-fpermissive]
       noexcept(noexcept(*declval<const I&>()))
                         ^~~~~~~~~~~~~~~~~~~~
In file included from /Users/Sutton/Code/cmcstl2/include/stl2/iterator.hpp:22:0,
                 from /Users/Sutton/Code/cmcstl2/include/stl2/detail/algorithm/generate.hpp:15,
                 from /Users/Sutton/Code/cmcstl2/test/algorithm/generate.cpp:21:
/Users/Sutton/Code/cmcstl2/include/stl2/detail/iterator/basic_iterator.hpp:685:31: note:   in call to ‘constexpr std::experimental::ranges::v1::basic_iterator< <template-parameter-1-1> >& std::experimental::ranges::v1::basic_iterator< <template-parameter-1-1> >::operator*() requires !(Next<C>)() [with C = std::experimental::ranges::v1::detail::back_insert_cursor<std::vector<int> >]’
     constexpr basic_iterator& operator*() noexcept
                               ^~~~~~~~

**Comment by CaseyCarter** [comment]
I haven't built the gcc branch yet to test properly, but I suspect that  a15c89dcaf9d7faf12c14d5a3cc4ce45c8881c91 will fix this. `Readable` wasn't properly requiring `operator*() const`, under the mistaken belief that the `typename reference_t<I>;` requirement implied it.

**Comment by CaseyCarter** [comment]
> I haven't built the gcc branch yet to test properly

Now that I have, the test is still broken. The issue is that `_counted_iterator::cursor` has a non-template member `read`:
```c++
decltype(auto) read() const
  noexcept(noexcept(*declval<const I&>()))
  requires InputIterator<I>();
```
Despite the associated constraints - `InputIterator<I>()` - not being satisfied, the compiler is substituting into the `noexcept` clause. I reported a similar bug (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69096) back in December, in which return type deduction was being performed before checking constraint satisfaction. This could be the same bug.

**Comment by CaseyCarter** [comment]
Slight modification of the test case from PR 69096:

```c++
template <class R>
constexpr bool has_adl = false;
template <class R>
requires
  requires(R&& r) { adl((R&&)r); }
constexpr bool has_adl<R> = true;

template <class T>
constexpr bool has_move = requires(T& t) { t.move(); };

template <class C>
struct basic_iterator
{
  C pos_;

  friend decltype(auto) adl(const basic_iterator& i)
  noexcept(noexcept(i.pos_.move()))
  requires has_move<decltype(i.pos_)>
  {
    return i.pos_.move();
  }
};

static_assert(!has_adl<basic_iterator<int>>);
```
results in errors from *both* the noexcept clause and return type deduction for the function that has unsatisfied constraints:
<pre>
casey@Semiregular:~$ ~/gcc-concepts-rewrite/bin/g++ -std=c++1z -fconcepts -I /home/casey/dev/cmcstl2/include foo2.cpp 
foo2.cpp: In instantiation of ‘decltype(auto) adl(const basic_iterator<int>&)’:
foo2.cpp:7:24:   required from here
foo2.cpp:19:28: error: request for member ‘move’ in ‘i.basic_iterator<int>::pos_’, which is of non-class type ‘const int’
   noexcept(noexcept(i.pos_.move()))
                     ~~~~~~~^~~~
foo2.cpp: In instantiation of ‘decltype(auto) adl(const basic_iterator<int>&)’:
foo2.cpp:7:24:   required from here
foo2.cpp:19:28: error: request for member ‘move’ in ‘i.basic_iterator<int>::pos_’, which is of non-class type ‘const int’
foo2.cpp:22:19: error: request for member ‘move’ in ‘i.basic_iterator<int>::pos_’, which is of non-class type ‘const int’
     return i.pos_.move();
            ~~~~~~~^~~~
foo2.cpp: In instantiation of ‘constexpr const bool has_move<int>’:
foo2.cpp:20:12:   required from here
foo2.cpp:11:46: error: request for member ‘move’ in ‘t’, which is of non-class type ‘int’
 constexpr bool has_move = requires(T& t) { t.move(); };
                                            ~~^~~~
</pre>

**Comment by CaseyCarter** [comment]
I may be mistaken in my interpretation of how constraints apply to non-template functions: they seem to be underspecified in P0121R0:

* [dcl.fct] paras 1 and 2 add an optional *requires-clause* to the grammar for function declarations, but doesn't specify any semantics for it. (Para 2 seems to inadvertently omit *trailing-return-type* from N4140)
* Para 5 and 6 discuss the "associated constraints" of a function declaration, but there's no connection between the *requires-clause* and these so-called "associated constraints". ([temp] tells me all about the associated constraints of template declarations, and how they are derived, but there is no equivalent for non-template function declarations.)
* [over.match.viable] *does* tell me that the associated constraints of a function must be satisfied for it to be viable, if only I knew where they came from ;)

**Comment by CaseyCarter** [comment]
Worked around in 23689d426768a1d153fae5a7204942f6d09c3866 by making `__counted_iterator::cursor::read` a template:
```c++
template <class II = I>
requires
  InputIterator<II>() && Same<I, II>()
decltype(auto) read() const
noexcept(noexcept(*declval<const II&>()))
{
  return *get();
}
```
