### ISSUE TITLE
N1452 problems

### ISSUE THREAD

**Issue by jicama** [CaseyCarter/cmcstl2#342]
Trying to build cmcstl2 with GCC modified to implement N1452 hits these errors:

include/meta/meta_fwd.hpp:298:20: error: return-type-requirement is not a type-constraint
include/stl2/detail/iterator/basic_iterator.hpp:215:23: error: return-type-requirement is not a type-constraint
include/stl2/detail/iterator/increment.hpp:143:20: error: return-type-requirement is not a type-constraint
include/stl2/detail/iterator/insert_iterators.hpp:118:33: error: return-type-requirement is not a type-constraint
include/stl2/view/subrange.hpp:40:26: error: return-type-requirement is not a type-constraint
include/stl2/view/subrange.hpp:41:26: error: return-type-requirement is not a type-constraint

**Comment by CaseyCarter** [comment]
Thank you! This will save me a couple of hours auditing *requires-expression*s for `->`s .
