### ISSUE TITLE
Compiler doesn't see subsumption of iterator concepts

### ISSUE THREAD

**Issue by CaseyCarter** [CaseyCarter/cmcstl2#4]
```
#include <stl2/iterator.hpp>

template <stl2::InputIterator>
constexpr bool f() { return false; }
template <stl2::ForwardIterator>
constexpr bool f() { return true; }

int main() {
    static_assert(f<int*>());
}
```
`error: call of overloaded ‘f()’ is ambiguous`

**Comment by CaseyCarter** [comment]
In `WeakInputIterator`:
```
template <class I>
concept bool WeakInputIterator() {
  return WeakIterator<I>() &&
    Readable<I>() &&
    requires (I& i, const I& ci) {
      typename IteratorCategory<I>;
      DerivedFrom<IteratorCategory<I>, weak_input_iterator_tag>();
      STL2_DEDUCTION_CONSTRAINT(i++, Readable);
      requires Same<ValueType<I>, ValueType<decltype(i++)>>();
      { *ci } -> const ValueType<I>&;
    };
}
```
Commenting out `STL2_DEDUCTION_CONSTRAINT(i++, Readable);` makes the test compile correctly.

**Comment by ericniebler** [comment]
Compiler bug?

**Comment by CaseyCarter** [comment]
I'm almost positive. My efforts to reduce a test case yesterday were unsuccessful: I found two different ways to ICE the compiler, and the final result after working around those issues compiles just fine. I think I'm just going to dump a preprocessed version of the test case in the first comment on Jason.

**Comment by ericniebler** [comment]
Great. I hope you reported the ICEs, too.

**Comment by CaseyCarter** [comment]
This issue is now [GCC bug #67018](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67018).

**Comment by CaseyCarter** [comment]
> Great. I hope you reported the ICEs, too.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67021 is my favorite. It ICEs, but compiles just fine without `#include <type_traits>`. Nothing in the program uses `type_traits`, or anything in namespace `std`.

**Comment by ericniebler** [comment]
Always be sure to add Andrew Sutton and Jason Merrill to the cc list of concept-gcc bugs.

**Comment by CaseyCarter** [comment]
Closed by the fix for GCC PR67018 - this test now works correctly.
