### ISSUE TITLE
ranges::less, etc. and Callable

### ISSUE THREAD

**Issue by cjdb** [CaseyCarter/cmcstl2#40]
Currently unable to pass `less<T>{}` to a function or class that takes a `Callable` parameter. Am I missing something in this example?

```cpp
void lt(Callable f)
{
   cout << f(1, 2) << '\n';
} 

int main()
{
   lt(ranges::less<int>{});
}
```

**Comment by ericniebler** [comment]
lt is a function that takes one argument that is capable with no arguments. less requires two arguments. Try:

void lt(Callable<int, int> f)
