### ISSUE TITLE
test/iterator/any_iterator and GCC 7

### ISSUE THREAD

**Issue by ericniebler** [CaseyCarter/cmcstl2#63]
There is some issue with inheriting constructors. It would be nice to know if any of our proposed interfaces are running afoul of recent language changes.

**Comment by CaseyCarter** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79143
```c++
struct base {
  base(int, int) {}
};

template<class>
struct derived : base {
  using base::base;
};

int main() {
  base(13, 42); // Fine
  derived<int>(13, 42); // Fine
  base{13, 42}; // Fine
  derived<int>{13, 42}; // Error
}
```

<pre>
prog.cc: In function 'int main()':
prog.cc:14:22: error: too many initializers for 'derived&lt;int>'
   derived&lt;int>{13, 42}; // Error
                      ^
prog.cc:14:22: error: could not convert '13' from 'int' to 'base'
</pre>

**Comment by CaseyCarter** [comment]
Even after applying the workaround for PR79143, `any_iterator`'s test will not compile with GCC trunk. It *does* compile with GCC6, even when the PR79143 workaround is activated manually.

**Comment by CaseyCarter** [comment]
Update:

This test is building again, but with caveats:
* `-Wstrict-aliasing` fires about a half-dozen during the build. These could be false positives. For now, the test builds with `-Wno-error=strict-aliasing` to allow the build to continue with these warnings.
* There's something weird going on with the `cursor::mixin` constructors that I think results in constraint recursion without the `explicit mixin(cursor)` constructor. This also needs investigation to determine if it's a  compiler bug or merely UB that was latent in earlier compilers.

**Comment by CaseyCarter** [comment]
These problems no longer manifest with GCC 7 trunk. That should mean that they will not trigger in 7.2 when it is released. For now, I'm going to make these workarounds conditional on GCC version being in [7.0,7.2) and call it good.
