### ISSUE TITLE
Eradicate initializer_list algorithm extensions

### ISSUE THREAD

**Issue by CaseyCarter** [CaseyCarter/cmcstl2#69]
...being careful not to remove the non-extension overloads that accept `initializer_list`.

**Comment by cjdb** [comment]
Are there any extensions that don't have `// .*Extension.*` above them, and are there any non-extensions that _might_ have `// .*Extension.*` above them?

**Comment by cjdb** [comment]
> Are there any extensions that don't have `// .*Extension.*` above them

Yes, evidenced by `count_if.hpp`.

**Comment by CaseyCarter** [comment]
> Yes, evidenced by count_if.hpp.

Curses, I thought I had managed to tag all of them. In any case, `min`, `max`, and `minmax` are the only algorithms specified to have `initializer_list` overloads.

**Comment by cjdb** [comment]
Hmm... I just checked out all of my edits, because they fail tests, and I thought I'd royally screwed up. Do I need to remove the tests too in that case?

**Comment by cjdb** [comment]
Previously on #69:

> Are there any algorithms that don't have `// .*Extension.*` that are in fact extensions?
> Yes, evidenced by `count_if.hpp`

**Comment by CaseyCarter** [comment]
> Do I need to remove the tests too in that case?

I'd be wary of inadvertently reducing test coverage. Maybe change the tests to use lvalue initializer lists a la:

```diff
-algorithm(foo, {1,2,3});
+auto some_list = {1,2,3};
+algorithm(foo, some_list);
```

**Comment by cjdb** [comment]
Got it, thanks for the heads up :)
