### ISSUE TITLE
Get rid of the concept test predicates in namespace models

### ISSUE THREAD

**Issue by CaseyCarter** [CaseyCarter/cmcstl2#79]
...to the extent possible.

**Comment by cjdb** [comment]
What's an example of this?

**Comment by CaseyCarter** [comment]
```c++
template<class T>
concept bool Foo() { /**/; }

namespace models {
    template <class>
    constexpr bool Foo = false;
    template <class T>
    requires __stl2::Foo<T>()
    constexpr bool Foo = true;
}
```
These allow you to test if type `T` satisfies concept `Foo`, e.g. in a `static_assert`:
```c++
static_assert(models::Foo<T>);
```
The intent of Concepts TS issue 29 (http://cplusplus.github.io/concepts-ts/ts-active.html#29) is to add support for evaluating a concept directly as if it defined a constexpr bool variable/function template:
```c++
static_assert(Foo<T>());
```
GCC has implementation support for such usage, although it did not when cmcstl2 was first implemented. Given that the issue is still open and doesn't yet have wording in the Concepts WP ([n4641](http://wg21.link/n4641) these days), I think it may be to soon to yank these from cmcstl2 after all.
