### ISSUE TITLE
Remove the remaining workarounds for GCC 79143

### ISSUE THREAD

**Issue by CaseyCarter** [CaseyCarter/cmcstl2#80]

**Comment by ericniebler** [comment]
There's still some problem there I don't yet understand. I couldn't remove them all.

**Comment by CaseyCarter** [comment]
> There's still some problem there I don't yet understand. I couldn't remove them all.

Yes, I took a stab at it last weekend and had issues. Considering that 79143 has been fixed, there's a new bug somewhere in there to file.
