### ISSUE TITLE
Remove deprecated functions

### ISSUE THREAD

**Issue by cjdb** [CaseyCarter/cmcstl2#82]
The following functions have deprecated overloads:

1. equal
2. is_permutation
3. mismatch
4. swap_ranges
5. transform
6. range/access.hpp

**Comment by CaseyCarter** [comment]
`range/access.hpp` is an internal header file, not a function, but the other five are specified to have those deprecated overloads. Why would we remove them?

**Comment by cjdb** [comment]
Ah, I didn't realise they were specified.
