### ISSUE TITLE
`decltype(__stl2::rend(declval<T&>()))` manifests as an error when T == forward_list<int>, but `decltype(__stl2::rbegin(declval<T&>()))` does not

### ISSUE THREAD

**Issue by cjdb** [CaseyCarter/cmcstl2#87]
Toying around with some container stuff, so I've defined these:

```cpp
template <class T>
using reverse_iterator_t =  decltype(__stl2::rbegin(declval<T&>()));

template <class T>
using reverse_sentinel_t =  decltype(__stl2::rend(declval<T&>()));

template <class X>
concept bool ReversibleContainer() {
   return Container<X>() &&
      BidirectionalRange<X>() &&
      requires(X x, const X cx) {
         typename reverse_iterator_t<X>; // works
         typename reverse_sentinel_t<X>; // fails when X = forward_list<int>
         typename const_reverse_iterator_t<X>; // works
   };
}
```

Interestingly, `reverse_iterator_t` works, but `reverse_sentinel_t` causes the [attached diagnostic](https://github.com/CaseyCarter/cmcstl2/files/792043/sentinel_diagnostic.txt).

Is there any particular reason why `reverse_iterator_t<foward_list<int>>` doesn't manifest as an error, but `reverse_sentinel_t<forward_list<int>>` does?

**Comment by CaseyCarter** [comment]
The implementation of `rbegin` is using `make_reverse_iterator` unqualified, so it gets `std::reverse_iterator<iterator_t<forward_list<int>>>` for `reverse_iterator_t` instead of `__stl2::reverse_iterator<iterator_t<forward_list<int>>>` which properly requires `Bidirectional<iterator_t<forward_list<int>>>()`.

Good catch ;)

**Comment by cjdb** [comment]
Thanks! That was driving me crazy this morning.
ReversibleContainer now enforces Gandalf-level rejections on `forward_list` and unordered containers :)
