### ISSUE TITLE
Is a matrix not Assignable?

### ISSUE THREAD

**Issue by adah1972** [CaseyCarter/cmcstl2#93]
OK, it is a little bit complicated. I am using the linear algebra library Armadillo, which defines a matrix as `arma::Mat<T>` class template, and a fixed matrix as `arma::Mat<T>::fixed<Rows, Cols>` nested class template. There are two tricky things:

- Armadillo returns a const lvalue reference for its `operator=` functions.
- `arma::Mat<T>::fixed<Rows, Cols>::operator=` returns a (const) `arma::Mat<T>`, which is convertible to `arma::Mat<T>::fixed<Rows, Cols>`.

After discussing with its author, I tried removing all the `const` in the return type of `operator=`. However, the second bullet still prevents the `Assignable` requirement from working. I tried changing

			requires(T t, U&& u) {
				{ t = (U&&)u } -> Same<T>&&;
			};

to

			requires(T t, U&& u) {
				{ t = (U&&)u } -> T;
			};

or

			requires(T t, U&& u) {
				{ t = (U&&)u } -> ConvertibleTo<T>&&;
			};

But I could not make it work. This hack works:

			requires(T t1, T t2, U&& u) {
				{ t1 = (t2 = (U&&)u) };
			};

I.e. the result of assignment can be used in assignment again. Not nice. Do you have a better solution? Or should we simply remove the return type check completely?

I think Armadillo’s approach is valid (for reusing the code), and its behaviour is quite normal without the concept checks. It would be a surprise that it should fail such a simple concept check. What change can be made to make it pass the concept check? (I think `arma::Mat` and `arma::Mat::fixed` should pass `Semiregular`—its `operator==` is a bit unconventional, though, and should fail `EqualityComparable` and thus `Regular`.)

**Comment by adah1972** [comment]
As the author of Armadillo accepted my patch to make its matrix `Semiregular`, this issue *may* be closed. However, it may be worth considering whether we want to loosen the requirements a little bit so that less surprise would be caused.

**Comment by ericniebler** [comment]
Encouraging developers to modify their code to make it more "normal" is exactly the point. I would say the concept is working fine and needs no loosening.

**Comment by CaseyCarter** [comment]
As Eric says, this is most definitely working as intended. Many of the Ranges TS concepts describe portions of the behavior of Regular types, because Regular types are fundamental to the design of C++ and the value-semantics-oriented design of its standard library. The concepts are essentially a recipe book for what Scott Meyers calls "do as the `int`s do." These concepts are as close as we can get to describing how C++ types "ought to" behave in the absence of other considerations, because these behaviors are in line with what the language and standard library have taught programmers to expect.

**Comment by adah1972** [comment]
This issue becomes more complicated than expected. There is a regression with my change under GCC. Such a simple program fails to build under GCC now:

```cpp
#include <iostream>
#include <armadillo>

int main()
{
    arma::mat33 X;
    X.fill(123);

    double y = 456;
    X = X / y;

    std::cout << X << std::endl;
}
```

GCC reports (while Clang does not have any problems):

test.cpp: In function `int main()`:
test.cpp:10:13: error: ambiguous overload for `operator=` (operand types are `arma::mat33` {aka `arma::Mat<double>::fixed<3ull, 3ull>`} and `arma::enable_if2<true, const arma::eOp<arma::Mat<double>::fixed<3ull, 3ull>, arma::eop_scalar_div_post> >::result` {aka `const arma::eOp<arma::Mat<double>::fixed<3ull, 3ull>, arma::eop_scalar_div_post>`})
`     X = X / y;`

`X / y` has type `const arma::eOp<arma::Mat<double>::fixed<3ull, 3ull>, arma::eop_scalar_div_post>`, while `X` is of type `arma::Mat<double>::fixed<3ull, 3ull>`. These are the relevant declarations I find:

```cpp
template<typename eT>
class Mat : public Base< eT, Mat<eT> >
  {
  …
  template<typename T1, typename eop_type> inline Mat&  operator=(const eOp<T1, eop_type>& X);
  …
  };

template<typename eT>
template<uword fixed_n_rows, uword fixed_n_cols> 
class Mat<eT>::fixed : public Mat<eT>
  {
  …
  using Mat<eT>::operator=;
  fixed& operator=(const fixed<fixed_n_rows, fixed_n_cols>& X);
  template<typename T1, typename eop_type> inline fixed& operator=(const eOp<T1, eop_type>& X);
  …
  };
```

Changing

```cpp
  template<typename T1, typename eop_type> inline fixed& operator=(const eOp<T1, eop_type>& X);
```

to

```cpp
  template<typename T1, typename eop_type> inline Mat& operator=(const eOp<T1, eop_type>& X);
```
solves the GCC build problem.

You can see some discussions in https://github.com/conradsnicta/armadillo-code/issues/20.

Do you have any insights whether GCC has a bug, or how this dilemma between ambiguity and concept-correctness can be resolved?

**Comment by adah1972** [comment]
Never mind, the problem I reported seemed to be due to a GCC bug, as the ambiguous overload issue is gone now with GCC 7.1.
