### ISSUE TITLE
Bug(?) causing private/public scoping issues

### ISSUE THREAD

**Issue by andyg7** [CaseyCarter/cmcstl2#95]
Hey everyone, 
First off this is repo is great, thanks a lot for all the concepts :). I recently included some of the code in a project of mine (https://github.com/andyg7/Graph-Library) and have noticed something weird. Whenever I include some of the stl2 code in my project, I seem to be able to access private member functions and variables in basically all classes/structs.

For example, the following does compile:
[does_compile.tiff.pdf](https://github.com/CaseyCarter/cmcstl2/files/906704/does_compile.tiff.pdf)
even though y is a private variable.

However, when I comment out the included files like this:
[does_not_compile.tiff.pdf](https://github.com/CaseyCarter/cmcstl2/files/906708/does_not_compile.tiff.pdf)
The code does not compile (as we would expect). 

Has anyone seen this issue before?

**Comment by CaseyCarter** [comment]
Minimal library-free (it's a compiler bug) reproducer:
```c++
template <class, class>
concept bool C1 = true;

template <class>
concept bool C2 = requires { { 42 } -> C1<int>; };

int main() {
    class A { int x; } a;
    a.x = 42;
}
```

This was news to me, but has already been reported as [GCC PR 78715](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78715).
